services:
  - type: web
    name: mm-estudio-landing
    runtime: node
    pullRequestPreviewsEnabled: false
    buildCommand: ""
    startCommand: node server.mjs

    envVars:
      - key: CONTACT_TO
        value: nicolasmgomez9441@gmail.com
      - key: CONTACT_SITE
        value: Mentes Modernas
